apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: order:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DB_URL
              value: sqlite:////data/orders.sqlite
            - name: INVENTORY_URL
              value: http://inventory:8000
            - name: RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq:5672/
            - name: RABBITMQ_QUEUE
              value: orders
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  selector:
    app: order
  ports:
    - port: 8000
      targetPort: 8000
